version: "3.7"

volumes:
    prometheus-data:

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest #v1.2.2
    container_name: slave_node_exporter
    command:
    - '--path.rootfs=/host'
    restart: unless-stopped
    env_file:
    - .env
    pid: host
    expose:
    - 9100
    volumes:
    - '/:/host:ro,rslave'
    logging:
      driver: loki
      options:
        loki-url: "http://10.25.66.143:3100/loki/api/v1/push" 

  prometheus:
    image: prom/prometheus:latest #v2.28.1
    user: root
    container_name: slave_prometheus
    restart: unless-stopped
    env_file:
    - .env
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus
    logging:
      driver: loki
      options:
        loki-url: "http://10.25.66.143:3100/loki/api/v1/push"  

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest #v0.38.6
    privileged: true
    container_name: slave_cAdvisor
    restart: unless-stopped
    env_file:
    - .env
    expose:
    - 8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    logging:
       driver: loki
       options:
        loki-url: "http://10.25.66.143:3100/loki/api/v1/push"

  promtail:
    image: grafana/promtail:latest
    container_name: slave_promtail
    restart: unless-stopped
    env_file:
    - .env
    volumes:
    - /Web:/Web:ro #Directorio de mayor profundidad en comun a todos los logs de la pc host. (SOLO LECTURA)
    - /home/:/home_server:ro
    - /root/:/root_user:ro
    - ./promtail.yml:/etc/promtail/promtail.yml
   #- ./positions.yaml:/tmp/positions.yaml
    command: -config.file=/etc/promtail/promtail.yml -config.expand-env=true # env vars
    logging:
      driver: loki
      options:
        loki-url: "http://10.25.66.143:3100/java/loki/api/v1/push"
